name: Site deploy test
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code to workspace
        uses: actions/checkout@v2
