name: Run ifconfig in Ubuntu container

on:
  push:
    branches:
      - main

jobs:
  ifconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Run ifconfig
        run: |
          sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
          apt-get update && apt-get install -y net-tools
          ifconfig
          apt install python3-pip -y
          pip3 --version
          pip3 install NumPy -i https://pypi.tuna.tsinghua.edu.cn/simple
          pip3 install statsmodels -i https://pypi.tuna.tsinghua.edu.cn/simple
          pip3 install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple
          pip3 install matplotlib -i https://pypi.tuna.tsinghua.edu.cn/simple
          pip install mkdocs-material

      # copy git 仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v2