name: GitHub Actions Demo1
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - run: apt update -y
