name: Run ifconfig in Ubuntu container

on:
  push:
    branches:
      - main

jobs:
  ifconfig:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: Run ifconfig
        run: |
          sudo sed -i 's/cn.archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
          apt-get update && apt-get install -y net-tools
          ifconfig
          apt install python3-pip -y
          pip3 -V
