name: Run ifconfig in Ubuntu container

on:
  push:
    branches:
      - main

jobs:
  ifconfig:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: Run ifconfig
        run: |
          apt-get update && apt-get install -y net-tools
          ifconfig
          pip3 -V
